const bookData = [
    {
      author: ["Burroughs, Edgar Rice"],
      language: "en",
      subject: [
        "Adventure stories",
        "PZ",
        "Fantasy fiction",
        "Tarzan (Fictitious character) -- Fiction",
        "PS",
        "Jungle animals -- Fiction",
      ],
      title: "The Beasts of Tarzan",
    },
    {
      author: ["Kipling, Rudyard"],
      language: "en",
      subject: [
        "India -- History -- 19th century -- Fiction",
        "Feral children -- Fiction",
        "Animals -- Fiction",
        "Jungles -- Fiction",
        "India -- Fiction",
        "PR",
        "Adventure stories, English",
        "Mowgli (Fictitious character) -- Fiction",
        "Short stories",
        "Jungle animals -- Fiction",
      ],
      title: "The Jungle Book",
    },
    {
      author: ["Sewell, Anna"],
      language: "en",
      subject: [
        "Historical fiction",
        "PZ",
        "PR",
        "Great Britain -- History -- 19th century -- Juvenile fiction",
        "Human-animal relationships -- Juvenile fiction",
        "Horses -- Juvenile fiction",
      ],
      title: "Black Beauty",
    },
    {
      author: ["Lofting, Hugh"],
      language: "en",
      subject: [
        "Fantasy literature",
        "PZ",
        "Human-animal communication -- Juvenile fiction",
        "Animals -- Juvenile fiction",
      ],
      title: "The Story of Doctor Dolittle",
    },
]